version: "{build}"

os: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  VULKAN_SDK: "C:\\VulkanSDK\\1.0.49.0"

init:
  - appveyor DownloadFile https://vulkan.lunarg.com/sdk/download/1.0.49.0/windows/VulkanSDK-1.0.49.0-Installer.exe -FileName vulkan-installer.exe
  - vulkan-installer.exe /S
  - rm -f vulkan-installer.exe

install:
  - git submodule update --init

build:
  parallel: true
  verbosity: minimal
